services:
  api:
    build: .
    container_name: functional-api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    command: [ "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4" ]